import { useState } from 'react'
import { DEBT_ITEMS, SEVERITY_META, SPRINT_META, COMPONENT_COLORS } from '../data/debtData'

const STATUS_COLORS = {
  'in-progress': '#0072BC', 'todo': '#D97706', 'planned': '#00BCCC', 'backlog': '#8C9BAB', 'done': '#00B753',
}

export default function RemediationPlan({ onNavigate }) {
  const [activeSprint, setActiveSprint] = useState('all')
  const [expandedId, setExpandedId] = useState(null)

  const totalSP   = DEBT_ITEMS.reduce((a,i) => a+i.effort, 0)
  const critCount = DEBT_ITEMS.filter(d => d.severity==='critical').length

  const grouped = activeSprint === 'all'
    ? DEBT_ITEMS
    : DEBT_ITEMS.filter(d => d.sprint === activeSprint)

  const sprintGroups = ['S1','S2','S3','S4']
  const itemsBySprint = s => DEBT_ITEMS.filter(d => d.sprint === s)
  const sprintSP = s => itemsBySprint(s).reduce((a,i) => a+i.effort, 0)
  const sprintNames = { S1:'Sprint 1',S2:'Sprint 2',S3:'Sprint 3',S4:'Sprint 4' }

  const SevBadge = ({sev}) => {
    const m = SEVERITY_META[sev]
    return <span style={{background:m.bg,color:m.color,border:`1px solid ${m.border}`,borderRadius:10,padding:'2px 7px',fontSize:10,fontWeight:700,textTransform:'uppercase'}}>{m.label}</span>
  }

  return (
    <div style={{ height:'calc(100vh - 54px)', display:'flex', flexDirection:'column', overflow:'hidden', background:'var(--offwht)' }}>

      {/* Sprint overview strip */}
      <div style={{ background:'white', borderBottom:'1px solid var(--lgray)', padding:'14px 24px', flexShrink:0 }}>
        <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:12 }}>
          <div>
            <h2 style={{ fontSize:17, fontWeight:700, fontFamily:'var(--font-serif)', color:'var(--navy)', letterSpacing:'-0.3px' }}>
              AI-Generated Remediation Plan
            </h2>
            <p style={{ fontSize:12, color:'var(--mgray)', marginTop:2 }}>
              {DEBT_ITEMS.length} issues · {totalSP} SP total · Generated by Claude in 8 seconds
            </p>
          </div>
          <div style={{ display:'flex', gap:10 }}>
            <button style={{ background:'var(--navy)', color:'white', border:'none', borderRadius:8, padding:'8px 16px', cursor:'pointer', fontSize:12.5, fontWeight:600, fontFamily:'var(--font-sans)' }}>
              ⬇ Export to Jira
            </button>
            <button style={{ background:'white', color:'var(--dgray)', border:'1px solid var(--lgray)', borderRadius:8, padding:'8px 16px', cursor:'pointer', fontSize:12.5, fontFamily:'var(--font-sans)' }}>
              📊 Full Report
            </button>
          </div>
        </div>

        <div style={{ display:'grid', gridTemplateColumns:'repeat(5,1fr)', gap:12 }}>
          {[['all','All Sprints',DEBT_ITEMS.length,totalSP,'var(--blue)'], ...sprintGroups.map(s => [s, sprintNames[s], itemsBySprint(s).length, sprintSP(s)])].map(([id,name,cnt,sp,col]) => {
            const m = SPRINT_META.find(x=>x.id===id) || { progress: id==='all' ? 45 : 0, status: 'all' }
            const isActive = activeSprint === id
            return (
              <div key={id} onClick={() => setActiveSprint(id)}
                style={{
                  background: isActive ? 'var(--navy)' : 'var(--offwht)',
                  borderRadius:10, padding:'10px 14px', cursor:'pointer',
                  border: isActive ? 'none' : '1px solid var(--lgray)',
                  transition:'all 0.15s',
                }}>
                <div style={{ display:'flex', justifyContent:'space-between', marginBottom:4 }}>
                  <span style={{ fontSize:12, fontWeight:700, color: isActive?'white':'var(--navy)' }}>{name}</span>
                  <span style={{ fontSize:11, color: isActive?'rgba(255,255,255,0.6)':'var(--mgray)' }}>{cnt} items</span>
                </div>
                <div style={{ fontSize:18, fontWeight:700, color: isActive?'var(--amber)':'var(--blue)', fontFamily:'var(--font-mono)' }}>
                  {sp} SP
                </div>
                {m.progress > 0 && (
                  <div style={{ height:4, background: isActive?'rgba(255,255,255,0.2)':'var(--lgray)', borderRadius:2, marginTop:8, overflow:'hidden' }}>
                    <div style={{ height:'100%', width:`${m.progress}%`, background: isActive?'var(--lblue)':'var(--blue)', borderRadius:2, transition:'width 0.8s ease' }} />
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>

      {/* Table */}
      <div style={{ flex:1, overflow:'auto', padding:'0 24px 20px' }}>
        <table style={{ width:'100%', borderCollapse:'collapse', marginTop:16 }}>
          <thead>
            <tr style={{ borderBottom:'2px solid var(--lgray)' }}>
              {['#','Component','Issue & AI Suggestion','Sev','Effort','Sprint','Status'].map(h => (
                <th key={h} style={{ padding:'8px 12px', textAlign:'left', fontSize:11, fontWeight:700, color:'var(--mgray)', textTransform:'uppercase', letterSpacing:'0.5px', whiteSpace:'nowrap' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {grouped.map((item, i) => {
              const isEx = expandedId === item.id
              const cc = COMPONENT_COLORS[item.component] || 'var(--mgray)'
              return (
                <>
                  <tr key={item.id} onClick={() => setExpandedId(isEx?null:item.id)}
                    style={{ background: isEx?'var(--offwht)':i%2===0?'white':'white', borderBottom:'1px solid var(--lgray)', cursor:'pointer' }}
                    onMouseEnter={e => { if(!isEx) e.currentTarget.style.background='var(--offwht)' }}
                    onMouseLeave={e => { if(!isEx) e.currentTarget.style.background='white' }}>
                    <td style={{ padding:'10px 12px', fontSize:11, fontFamily:'var(--font-mono)', color:'var(--mgray)' }}>
                      {isEx?'▼':'▶'} {item.id}
                    </td>
                    <td style={{ padding:'10px 12px' }}>
                      <span style={{ background:`${cc}18`, color:cc, border:`1px solid ${cc}30`, borderRadius:10, padding:'2px 8px', fontSize:10.5, fontWeight:600 }}>
                        {item.component}
                      </span>
                    </td>
                    <td style={{ padding:'10px 12px', maxWidth:420 }}>
                      <div style={{ fontSize:13, fontWeight:600, color:'var(--navy)', lineHeight:1.3, marginBottom:4 }}>{item.title}</div>
                      <div style={{ fontSize:11.5, color:'var(--mgray)', lineHeight:1.4 }}>
                        ✦ {item.aiSuggestion.slice(0,80)}{item.aiSuggestion.length>80?'…':''}
                      </div>
                    </td>
                    <td style={{ padding:'10px 12px' }}><SevBadge sev={item.severity} /></td>
                    <td style={{ padding:'10px 12px', fontFamily:'var(--font-mono)', fontSize:14, fontWeight:700, color: item.effort>=8?'var(--red)':item.effort>=5?'#D97706':'var(--green)' }}>
                      {item.effort} SP
                    </td>
                    <td style={{ padding:'10px 12px', fontSize:13, fontWeight:700, color:'var(--blue)', fontFamily:'var(--font-mono)' }}>{item.sprint}</td>
                    <td style={{ padding:'10px 12px' }}>
                      <span style={{ background:`${STATUS_COLORS[item.status]}18`, color:STATUS_COLORS[item.status], borderRadius:10, padding:'3px 8px', fontSize:11, fontWeight:600 }}>
                        {item.status.replace('-',' ')}
                      </span>
                    </td>
                  </tr>
                  {isEx && (
                    <tr key={`${item.id}-ex`} style={{ background:'var(--offwht)', borderBottom:'2px solid var(--lgray)' }}>
                      <td colSpan={7} style={{ padding:'14px 18px 14px 48px' }}>
                        <div style={{ display:'grid', gridTemplateColumns:'1.2fr 1fr', gap:20 }}>
                          <div>
                            <p style={{ fontSize:11, fontWeight:700, color:'var(--mgray)', textTransform:'uppercase', letterSpacing:'0.5px', marginBottom:6 }}>Full AI Recommendation</p>
                            <div style={{ background:'rgba(0,114,188,0.06)', border:'1px solid rgba(0,114,188,0.18)', borderRadius:8, padding:'12px', fontSize:13, lineHeight:1.6, color:'var(--dgray)' }}>
                              ✦ {item.aiSuggestion}
                            </div>
                            {item.breakdown && (
                              <div style={{ marginTop:12 }}>
                                <p style={{ fontSize:11, fontWeight:700, color:'var(--mgray)', textTransform:'uppercase', letterSpacing:'0.5px', marginBottom:6 }}>Issue Breakdown</p>
                                {item.breakdown.map(b => (
                                  <div key={b.name} style={{ display:'flex', justifyContent:'space-between', padding:'6px 0', borderBottom:'1px solid var(--lgray)', fontSize:12 }}>
                                    <span style={{ color:'var(--dgray)' }}>{b.name}</span>
                                    <span style={{ fontWeight:700, fontFamily:'var(--font-mono)', color:SEVERITY_META[item.severity]?.color }}>{b.count}</span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                          <div>
                            <p style={{ fontSize:11, fontWeight:700, color:'var(--mgray)', textTransform:'uppercase', letterSpacing:'0.5px', marginBottom:6 }}>File Details</p>
                            {item.file && item.file !== 'Multiple' && (
                              <div style={{ background:'var(--navy)', borderRadius:8, padding:'10px 14px', fontFamily:'var(--font-mono)', fontSize:12.5, color:'rgba(200,220,255,0.85)', marginBottom:10 }}>
                                📄 {item.file}{item.lines>0 ? <span style={{ color:'#FCA5A5' }}> · {item.lines.toLocaleString()} lines</span> : ''}
                              </div>
                            )}
                            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:8 }}>
                              {[['Module',item.module],['Category',item.category?.replace(/-/g,' ')],['Sprint',item.sprint],['Effort',`${item.effort} SP`]].map(([l,v]) => (
                                <div key={l} style={{ background:'white', borderRadius:6, padding:'8px 10px' }}>
                                  <div style={{ fontSize:10, color:'var(--mgray)', marginBottom:2, fontWeight:500 }}>{l}</div>
                                  <div style={{ fontSize:12, fontWeight:600, color:'var(--navy)', textTransform:'capitalize' }}>{v}</div>
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>
                      </td>
                    </tr>
                  )}
                </>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div style={{ background:'var(--navy)', padding:'14px 24px', display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:20, flexShrink:0 }}>
        <div>
          <div style={{ fontSize:10, color:'rgba(255,255,255,0.5)', textTransform:'uppercase', letterSpacing:'0.8px', marginBottom:2 }}>Projected Savings</div>
          <div style={{ fontSize:22, fontWeight:700, color:'var(--amber)', fontFamily:'var(--font-serif)' }}>£312,000</div>
          <div style={{ fontSize:11, color:'rgba(255,255,255,0.5)', marginTop:2 }}>remediation cost avoided · 18 months · 43% custom code reduction</div>
        </div>
        <div>
          <div style={{ fontSize:10, color:'rgba(255,255,255,0.5)', textTransform:'uppercase', letterSpacing:'0.8px', marginBottom:2 }}>AI Detection Confidence</div>
          <div style={{ fontSize:22, fontWeight:700, color:'var(--green)', fontFamily:'var(--font-serif)' }}>94%</div>
          <div style={{ fontSize:11, color:'rgba(255,255,255,0.5)', marginTop:2 }}>avg. confidence · &lt;3% false positive rate in 90 days</div>
        </div>
        <div style={{ display:'flex', gap:10, alignItems:'center' }}>
          <button style={{ flex:1, background:'var(--blue)', color:'white', border:'none', borderRadius:8, padding:'10px', cursor:'pointer', fontSize:12.5, fontWeight:600, fontFamily:'var(--font-sans)' }}>
            ⬇ Export to Jira
          </button>
          <button style={{ flex:1, background:'rgba(255,255,255,0.08)', color:'white', border:'1px solid rgba(255,255,255,0.15)', borderRadius:8, padding:'10px', cursor:'pointer', fontSize:12.5, fontFamily:'var(--font-sans)' }}>
            🔔 Set Alerts
          </button>
        </div>
      </div>
    </div>
  )
}
